### ISSUE TITLE
After adding audit-argument-checks starts failing

### ISSUE THREAD

**Issue by StorytellerCZ** [jamauro/pub-sub#2]
After adding the package and enabling cache, the [audit-argument-checks](https://docs.meteor.com/packages/audit-argument-checks.html) started failing on various publications.
For example:
```
I20240311-11:17:15.638(1)? Exception from sub manager.clientDetails id zHTFojrLoGXydbg8c Error: Did not check() all arguments during publisher 'manager.clientDetails'
I20240311-11:17:15.638(1)?     at ArgumentChecker.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:515:13)
I20240311-11:17:15.638(1)?     at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:122:16)
I20240311-11:17:15.638(1)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1935:18)
I20240311-11:17:15.638(1)?     at packages/ddp-server/livedata_server.js:1160:9
I20240311-11:17:15.638(1)?     at packages/meteor.js:365:18
I20240311-11:17:15.638(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
I20240311-11:17:15.638(1)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1159:60)
I20240311-11:17:15.638(1)?     at Subscription.subscriptionProto._runHandler (packages/mdg:meteor-apm-agent/lib/hijack/wrap_subscription.js:12:24)
I20240311-11:17:15.639(1)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:970:9)
I20240311-11:17:15.639(1)?     at Session.sub (packages/ddp-server/livedata_server.js:709:12)
I20240311-11:17:15.639(1)?     at packages/mdg:meteor-apm-agent/lib/hijack/wrap_session.js:77:34
I20240311-11:17:15.639(1)?     at packages/meteor.js:365:18
I20240311-11:17:15.639(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)
I20240311-11:17:15.639(1)?     at Session.sessionProto.protocol_handlers.sub (packages/mdg:meteor-apm-agent/lib/hijack/wrap_session.js:76:44)
I20240311-11:17:15.639(1)?     at packages/ddp-server/livedata_server.js:639:43
```

The particular publication looks like this:
```
Meteor.publish('manager.clientDetails', async function () {
  this.unblock()
  const userId = Meteor.userId()
  if (!userId) return this.ready()
  const isClientManager = await Roles.userIsInRoleAsync(
    userId,
    ROLES_GLOBAL.CLIENT_MANAGER,
    { anyScope: true }
  )
  if (!isClientManager) return this.ready()
  const clientId = getClientIdFromRole(userId)
  if (!clientId) return this.ready()
  return ClientsCollection.find(clientId, { limit: 1, sort: { name: 1 } })
})
```

Removing the package fixes the issue. Any ideas?

**Comment by jamauro** [comment]
@StorytellerCZ thanks for reporting. I just published `v0.1.3` that should fix this issue.
